plugin.xml
src/android/XWalkCordovaCookieManager.java
src/android/XWalkCordovaWebView.java

This allows plugins to access the Crosswalk webview's cookie manager.
/cc @agrieve @infil00p
Requires apache/cordova-android#151

CB-5059 Add a CookieManager abstraction for Crosswalk.

---

libs/xwalk_core_library/xwalk.gradle

Crosswalk engine have been tested in mobile-spc and owned functionality tests with Crosswalk-11, and it was our plan to be released.

Use Crosswalk-11 for Cordova-android 4.0 release

---

src/android/XWalkCordovaResourceClient.java

Remove `shouldOverrideUrlLoading` from `CordovaWebViewEngine.Client`.
It's logic that's pretty webview-specific, so it doesn't make sense to  share.

Update to work with cordova-android's commit "a6da46a00e3f4c5bb334077274e4ac4759295fc2"

---

src/android/XWalkCordovaCookieManager.java
src/android/XWalkCordovaResourceClient.java

The ErrorCodeConversionHelper is a helper class to map native error code about
loading a page to Android specific ones. It has been called in the crosswalk runtime
libray before callback onReceivedError.

Delete duplicate conversion of native error code

---

src/android/XWalkCordovaView.java

I actually thought this was already the default, but turns out I was wrong. It really should be since 99% of Cordova apps don't need a TextureView, and it's better on battery to use SurfaceView.
Related to https://github.com/MobileChromeApps/mobile-chrome-apps/issues/538

Make webview use a SurfaceView by default

---

src/android/XWalkCordovaUiClient.java

Chromium has already implemented a better file chooser for android,
so bypass that implemented by Cordova.
Cherry pick it from Crosswalk-cordova
https://github.com/crosswalk-project/crosswalk-cordova-android/commit/ac6eb0958a3c4a3ddcb04decb7fb1ba9ac7f66f7
BUG=XWALK-4437

Fix issue of failing to launch camera when tapping input tag.

---

hooks/after_plugin_install/000-apply_cli_options.js
platforms/android/xwalk.gradle
plugin.xml

Use the parameter of LIB_MODE to specify the usage of Crosswalk runtime library
when installing the plugin, Use shared mode like --variable LIB_MODE="shared".
Also user can specify different Crosswalk version using a <preference> tag within your config.xml
The version of 13 in embedd mode
<preference name="xwalkVersion" value="org.xwalk:xwalk_core_library_beta:13+" />
<preference name="xwalkVersion" value="xwalk_core_library_beta:13+" />
The version of 13 in shared mode
<preference name="xwalkVersion" value="org.xwalk:xwalk_shared_library_beta:13+" />
<preference name="xwalkVersion" value="xwalk_shared_library_beta:13+" />
The used mode will depend on the preference of {{lib_mode}}
<preference name="xwalkVersion" value="13+" />
<preference name="xwalkVersion" value="13" />

Add a varibale of library mode when installing plugin

---

hooks/after_plugin_install/000-apply_cli_options.js
plugin.xml

Fix disable-pull-to-refresh-effect have no effect after setting the flag.
Can set multiple commandlines in the variable like
--variable CROSSWALK_ANDROID_COMMANDLINE="--disable-pull-to-refresh-effect --show-fps-counter"

Fix the issue of xwalk commandline

---

plugin.xml

Originally added to cordova-android:
https://github.com/apache/cordova-android/commit/4a67dd2e28aed257c85b75c11026ae7a2a19c2ad
These instead should only be added for crosswalk by relegating them to
its plugin

Permissions needed for detecting connection status

---

platforms/android/src/org/crosswalk/engine/XWalkWebViewEngine.java

Fix the issue app crashed when using cordova-plugin-splashscreen
BUG=XWALK-4820

Don't reflect method before xwalk ready

---

package.json

The Git links and issue tracker in package.json needed updating since the plugin source have moved to the crosswalk-project organization in Github, and Jira is used by the Crosswalk team to track issues.

Update repository and issue tracker information in pacakge.json

---

hooks/after_plugin_install/000-shared_mode_special.js

- If the project's config.xml already contains <preference name=xwalk* /> elements,
do not define variables already defined.
BUG=XWALK-5043

Do not override user-defined variables in config.xml

---

plugin.xml

This change allows easy install the plugin in Visual Studio 2015 directly from github repo.

fix android namespace in plugin.xml

---

hooks/update_config.js

Since 5.3.4 cordova won't contain `ConfigParser` and `xml-helpers` modules so hooks will became broken. For more details and repro steps see corresponding JIRA issue: https://issues.apache.org/jira/browse/CB-9834

Prevent hooks failures in newest cordova versions

---

README.md
platforms/android/src/org/crosswalk/engine/XWalkCordovaView.java
platforms/android/src/org/crosswalk/engine/XWalkWebViewEngine.java

Don't use the Cordova upstream's preference named BackgoundColor,
It will be crashed because of calling the API before xwalk ready.
BUG=XWALK-5240

Set background color with the preference of xwalkBackgroundColor

---

plugin.xml

cordova-plugman version 4.2.0 doesn't exist, however cordova-lib@4.2.0
does and makes sense for the gradleReference requirement

fix broken plugman engine tag

---

plugin.xml

This reverts commit a39c31ffb289d8502660dabe0c7ac74768fa78b5.
Cordova-lib is not included in the list of default engines that tag supports.
The deault engines define in default-engines.js.
Plugman will get the version of cordova-plugman from cordova-lib, so
the version of them are same.
BUG=XWALK-5633

Revert "fix broken plugman engine tag"

---

platforms/android/src/org/crosswalk/engine/XWalkCordovaUiClient.java

Don't add the annotation of @Override before the function so that it will be compatible
with the crosswalk before the version of 17.
The commit in xwalk core library is
https://github.com/crosswalk-project/crosswalk/pull/3344#issuecomment-154415589

Public the three APIs align with xwalk core library

---

platforms/android/src/org/crosswalk/engine/XWalkWebViewEngine.java

Allow setting the web view zOrderOnTop from config.xml. 
This is useful when using this plugin together with plugins like https://github.com/mapsplugin/cordova-plugin-googlemaps which require the crosswalk web view to be drawn on top of them.

Set z order of web view with the preference ZOrderOnTop.

---

hooks/update_config.js

Now you can set multiple command line options like that
cordova plugin add cordova-plugin-crosswalk-webview --variable XWALK_COMMANDLINE="--ignore-gpu-blacklist --enable-accelerated-2d-canvas --enable-gpu-rasterization --disable-pull-to-refresh-effect"

 multiple command line options

---

platforms/android/src/org/crosswalk/engine/XWalkCordovaView.java
platforms/android/src/org/crosswalk/engine/XWalkWebViewEngine.java

Load all extension sub-folders under assets/xwalk-extensions.
Employ Cordova plugin to enforce XWalkView get onNewIntent() and
onActivityResult() callback.
BUG=XWALK-5757

Support loading external extensions.

---

platforms/android/src/org/crosswalk/engine/XWalkWebViewEngine.java

Customer can listen the callback of onMessage in CordovaPlugin, also can
add plugin service to receive the message in CordovaActivity.

Send the message of xwalk's ready to plugin

---

platforms/android/xwalk.gradle
plugin.xml

Only embedded 32 bit crosswalk will generate two apks by default.
BUG=XWALK-6260

Pack one apk at shared mode

---

package.json
platforms/ios/src/XWalkNavigationDelegate.h
platforms/ios/src/XWalkNavigationDelegate.m
platforms/ios/src/XWalkUIDelegate.h
platforms/ios/src/XWalkUIDelegate.m
platforms/ios/src/XWalkWebViewEngine.h
platforms/ios/src/XWalkWebViewEngine.m
plugin.xml

As cordova-cli upgraded to v6.0.0 and cordova-ios upgraded to v4.0.1,
a new interface for web engine has been introduced, which makes it
easier to embed a WKWebView based third party WebView. Our
implementation is based on this new interface. Within this patch we've
Created a new XWalkWebViewEngine which wraps the XWalkView as its
webview, and implemented the required delegates.
BUG=XWALK-4911

[iOS] Enabled XWalkView within Cordova Crosswalk Plugin.

---

hooks/update_config.js

To fix the error I was getting with the cordova create:
```
ReferenceError: name is not defined
at [object Object].addPreferences (update_config.js:116:13)
at main (000-shared_mode_special.js:11:27)
at module.exports (000-shared_mode_special.js:3:36)
```

Add missing vars to fix ReferenceErrors in Node v4

---

platforms/android/xwalk.gradle

Run the following command to reproduce the error:
```
cordova build android -- --gradleArg=-PcdvBuildMultipleApks=false
```
It doen't matter if `cdvBuildMultipleApks` is set to `true` or `false`.
Following error is thrown:
```
Failed to notify ProjectEvaluationListener.afterEvaluate(), but primary configuration failure takes precedence.
java.lang.IllegalStateException: buildToolsVersion is not specified.
at com.google.common.base.Preconditions.checkState(Preconditions.java:176)
at com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.java:599)
at com.android.build.gradle.BasePlugin$10$1.call(BasePlugin.java:566)
at com.android.build.gradle.BasePlugin$10$1.call(BasePlugin.java:563)
at com.android.builder.profile.ThreadRecorder$1.record(ThreadRecorder.java:55)
at …
```

Fixes exception thrown when cdvBuildMultipleApks is set via the command line options

---

platforms/android/src/org/crosswalk/engine/XWalkCordovaUiClient.java

onPageLoadStarted will not be called when the contents of an embedded
frame changes, however, it should be called when jumping to a new link.
This is the same action with XWalk embedding API and WebView.
This patch also correct some confusions in comments and log.
BUG=XWALK-6295

[Android] onPageLoadStarted should aware the jump to a new link

---

README.md

otherwise, the old apk will be used for the emulator.

add hint to run cordova clean before building

---

hooks/update_config.js
plugin.xml

After much discussion and analysis of the market,
we have decided to discontinue support for Android 4.0 (ICS) in Crosswalk starting with version 20.
BUG=XWALK-7083

Crosswalk 20 don't support Android 4.0

---

platforms/android/src/org/crosswalk/engine/XWalkWebViewEngine.java

Required for Cordova-Android v6 compatibility with the new (threadsafe) bridge method: https://github.com/apache/cordova-android/pull/320

Implement evaluateJavascript method for Cordova 6

---

platforms/android/src/org/crosswalk/engine/XWalkWebViewEngine.java

This allows Crosswalk to use the evaluateJavascript bridge.
Background Info: https://lists.apache.org/thread.html/e886806222f00276e45e06fe549a4d37aff5563a5f760a8f4f10e8b0@%3Cdev.cordova.apache.org%3E

Add the JSEval bridge mode

---

package.json
plugin.xml

Hey guys,
Due to some recent changes (https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview/pull/100) crosswalk cannot be built for cordova-android@<6 anymore
To address that, engine versions should be updated in plugin.xml as well as in package.json
**Important**: Please note that my changes in package.json are assuming that next crosswalk version is 2.2.0
If that's not true, it should be updated to a correct version number upon release.

Update cordova-android dependency versions

---

platforms/android/xwalk.gradle

This is a fix for https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/337
Repro (cordova@6.4.0):
```
cordova create crosswalk-problem
cd crosswalk-problem
cordova platform add android
cordova plugin add https://github.com/phonegap/phonegap-plugin-barcodescanner
cordova plugin add https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview
cordova compile
```

Override cdvMinSdkVersion if it's lower than needed

---

hooks/update_config.js

Follow-up to e581761 ("fixed compatibility issues with
cordova-android@7.0.0"). Further comments in #188 indicate that hardcoding
'/' as the path separator when calling fs.existsSync() does not work well on
Windows.
Use path.join() everywhere as suggested by @nbinand.

update_config.js: Do not hardcode path separator.

---

platforms/android/xwalk.gradle

Since gradle 3.0 the compile option is deprecated. They request us to use implementation instead.
More info: https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html

Changes deprecated compile to implementation
