README.md
The expected option is minSdkVersion
=> Fixing wrong example

hooks/after_plugin_install/000-apply_cli_options.js
Fix installed error if there is no the option of variable.
Fix default preference don't configure to config.xml.
=> Configure default preference to config.xml

platforms/android/src/org/crosswalk/engine/XWalkWebViewEngine.java
Add extra plugin to get the event from the activity and handle the
initialization by XWalkActivityDelegate which provided by the
infrastructure.
=> Add support for shared mode

platforms/android/src/org/crosswalk/engine/XWalkWebViewEngine.java
Add XWalkInit plugin when loading the url instead of initializing the
engine
=> Fixed assert error of XWalkInit plugin

README.md, hooks/after_plugin_install/000-shared_mode_special.js, hooks/before_plugin_uninstall/000-shared_mode_special.js, plugin.xml
The default variables need to be configured in the js.
Remove those preferences at uninstall time.
=> Configure preference in config.xml with hooks

hooks/after_plugin_install/000-shared_mode_special.js, hooks/before_plugin_uninstall/000-shared_mode_special.js, hooks/update_config.js
Change the name of variables from XWALK_VERSION to xwalkVersion.
=> Configure the default variables in plugin.xml

platforms/android/xwalk.gradle, plugin.xml
Use the correct minSdkVersion comparing with the preference from config.xml.
Add the option of "--variable BUILD_MULTIPLE_APKS=false" if build the architectures
in one apk.
=> Don't ignore the minSDKVersion preference from config.xml

platforms/android/src/org/crosswalk/engine/XWalkWebViewEngine.java
Add a line to config.xml to configure the User Agent:
`<preference name="xwalkUserAgent" value="Custom UA" />`
BUG=5148
=> Adding User Agent configuration preference

plugin.xml
=> Update default crosswalk version to 15

hooks/after_build/000-build_64_bit.js, hooks/before_build/000-build_64_bit.js, hooks/update_config.js, platforms/android/xwalk.gradle, plugin.xml
Customer can use "cordova build android --xwalk64bit" to generate 64bit apks.
BUG=XWALK-6085 XWALK-5218
=> Build 64-bit apks

platforms/android/src/org/crosswalk/engine/XWalkCordovaClientCertRequest.java, platforms/android/src/org/crosswalk/engine/XWalkCordovaHttpAuthHandler.java, platforms/android/src/org/crosswalk/engine/XWalkCordovaResourceClient.java, plugin.xml
=> [Android] Adding handlers for auth and certs

platforms/android/src/org/crosswalk/engine/XWalkWebViewEngine.java
Add the plugin for activity delegate into XWalkWebViewEngine.init()
instead of loadUrl to make sure activity delegate can receive the
onResume callback even if loadUrl has not been invoked.
=> [Android] Fix the error that xwalk is not initialized without loading url

hooks/update_config.js, platforms/android/xwalk.gradle, plugin.xml
Specify lite with the variable of XWALK_MODE at install plugin time.
=> [Android] Support lite mode in the plugin

platforms/android/src/org/crosswalk/engine/XWalkCordovaClientCertRequest.java, plugin.xml
=> Handle getKeyTypes and getPrincipals

hooks/update_config.js, platforms/android/xwalk.gradle, plugin.xml
5.2.0 version of cordova-lib is support the Default Variables that is tracked with CB-9162.
=> Configure xwalk preference with default values

platforms/android/xwalk.gradle
=> Fix the issue of failing to pack CIRC

platforms/android/src/org/crosswalk/engine/XWalkWebViewEngine.java
=> Pause timers when app switched to background

platforms/android/src/org/crosswalk/engine/XWalkCordovaUiClient.java, platforms/android/src/org/crosswalk/engine/XWalkFileChooser.java, platforms/android/src/org/crosswalk/engine/XWalkWebViewEngine.java, plugin.xml
- Use new XWalkFileChooser.
- Request dangerous persmisions dynamically for Marshmallow and above.
BUG=XWALK-7281
=> [Android] Support new file chooser

platforms/android/src/org/crosswalk/engine/XWalkWebViewEngine.java
Eliminates the incompatibility problem of file chooser on
Android 4.x device.
=> Fixed crash of file chooser

platforms/android/src/org/crosswalk/engine/XWalkWebViewEngine.java
Reverts crosswalk-project/cordova-plugin-crosswalk-webview#102
=> Revert "Pause timers when app switched to background"

README.md, hooks/update_config.js, package.json, platforms/android/xwalk.gradle, plugin.xml
fixes #188, credits to @philoskim
=> fixed compatibility issues with cordova-android@7.0.0
